services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      db: # ajout du healthcheck
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: sh -c "npx prisma migrate deploy && node dist/main"
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # ajout du healthcheck pour s'assurer que la base de données est prête avant de démarrer le backend
      test: ["CMD-SHELL", "pg_isready -U user -d transcendence"]
      interval: 3s
      timeout: 3s
      retries: 10



volumes:
  pgdata:
