services:

  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - transcendence

  frontend:
    build: ./frontend
    expose:
      - "3000"
    env_file:
      - ./.env
    restart: always
    networks:
      - transcendence

  backend:
    build: ./backend
    expose:
      - "4000"
    depends_on:
      db:
        # ajout du healthcheck
        condition: service_healthy
    env_file:
      - ./backend/.env
      - ./.env
    volumes: # migration des schema directement lié creer sur le docker apparait dans le local
      - ./backend/prisma:/app/prisma
    command: sh -c "npx prisma migrate deploy && node dist/main"
    restart: always
    networks:
      - transcendence

  db:
    image: postgres:15
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-transcendence}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-transcendence}" ]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: always
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  pgdata:
